// Generated by 'unplugin-vue-components' — 提交版本，开发时由插件自动刷新
// 该声明保证首次 `vue-tsc --noEmit` 在插件生成前即可通过。
// 实际全局组件类型在 dev/build 时由插件按 Base / Business 目录补全。
export {}
declare module 'vue' {
  export interface GlobalComponents {}
}
